mecacosite/home/urls.py
from django.urls import path, re_path
from .import views
app_name = 'home'
urlpatterns = [
    path('',views.home, name='home'),
    path('product/', views.all_product, name = 'product'),
    path('detail/<int:id>/', views.product_detail, name='detail'), # baraie safhe joziat mahsol. va  ba <id> migoem ke hamrah in url id 
    # ham miaiad va noee id ra ham moshakhas mikonim ke integer as
    # path('category/<int:id>/', views.all_product, name='category'),# vaghti roie oic yek category click kardim marabebarad 
    # be safe mahsolat . ama faghat mahsolat an daste ra neshan dahad. va views jadid neminevisim va az views all-product estefade m

    # alan url bala ke bevasile id kar mikard ra bevasile slug migoeim kar konad.
    # path('category/<slug:slug>/', views.all_product, name='category'),
    #vaghti ma az name daste bandi haie farsi estefadeh konim be ma error midahad dar url  haie ke ba slug misazim ya id:
    # pas baiad az re_path estefade konim va baiad az re_path(rejects) estefade konim vaki ma kalak mizanim va noesh ra nemigoeim
    # ke slug ast:
    # path('category/<slug>/', views.all_product, name='category'),
    
    # alan mikhahim dar url alave bar slug id ra ham dar url neshan dahad
    path('category/<slug>/<int:id>/', views.all_product, name='category'),


]  

mecacosite/mecacosite/urls.py
from django.contrib import admin
from django.urls import path, include

#baraie estefade az static aval do method zir ra farakhani mikonim va sepas path marbot be an ra ezafe mikonim:
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), # baraie amniat address admin ra taghir bedim
    path('',include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#baraie static va media file ha mibasha kod bala

mecacosite/home/views.py
# from unicodedata import category
from itertools import product
from.models import *
from django.shortcuts import render, get_object_or_404
# get_object_or_404 baraie zamani ast ke vaghti safee ke karbar amdan ya sahvan id ya slug an ra eshtebah mizanad khata ha ra
#neshan nadahad ta so estefade shavad az etelaat ma va peigham page not find 404 neshan dadeh shavad
from django.http import HttpResponse
#har url ma yek function ast ke ma baraie page home va product ijad kardim. ama baraie estefade az template va
# models baiad az render estefade konim bejaie Httprespance. ke yek request migirad va yek templates name
# def home(request):
#     return HttpResponse('به وب سایت مکاکاکو سرویس خوش آمدید')
#
# def all_product(request):
#     return  HttpResponse('صفحه محصولات ')

#************************************************************************************************************

"""
    @estefade az render
    baiad template bases khod ra dar root besazim. va bad be setting miravamim va dar DIRS:
    template ra be jango moarefi konim. vaghti az BADE_DIR estefade mikonim eshare be root ma darad
    alan baraie har safhe yek fail html misazim
    mishavad 2 views ra be yek file html rabt dad
    render 3 ta meghdar migirad ke felan 2 ta estefade mikonim
"""
# def home(request):
#      return render(request, 'home.html')
#
# def all_product(request):
#     return  render(request, 'product.html')

#****************************************************************************************************************

"""
    alan ma file haie html ra az root site bardashtim va be app entegha dadim ke address an be sorat zir mishavad 
    alan file base.html ra dar template root misazim ta baghie ers bari konan azash
"""

def home(request):
    #namaiesh hame daste bandi ha az dakhel DB
    # category = Category.objects.all()

    # baraie inke vaghti daste bandi to dar to ijad mikonim image nazarim error nadagad az filter estefade mikonim

    category = Category.objects.filter(sub_cat=False)# migoeim anhaei ra biar ke daste bandi asli hastand va bolianfield anha 
    #dar filed sub_cat models Category barabar false bashad va sub category bashand

    #hala da ghaleb dictionary query bala ra migirim va namaiesh midahim
    #hala miravim be home.html va yek for mizanim baraie namaiesh
    return render(request, 'home/home.html',{'category':category})

#-------------------------------------------------------------------------------

#namayesh products ha
# def all_product(request, slug=None):#aval ba id ke az url migereftim kar mikard ama alan ba slug :
# def all_product(request, id=None): #alave bar request id ham az url miaiad. amabarabar none gharar midim yani agar karbar 
    #mostaghim roie id zad yani az url id ersal nashode va error nemidahad va miravad be safhe product

def all_product(request, slug=None, id=None):#baraie inke ham slug va ham id ra neshan dahim
    products = Product.objects.all()
    #mikhahim vaghti roie daste bandi ha click kardim mara bebarad be safhe mahsolat ama faghat mahsolat an daste bandi ke
    # entekhab kardim namayesh dade shavad
    #tamam dastebandi ha ra begir . baraie inke vaghti roie daste bandi ha click kardim
    # beravad be safhe product ama faghat mahsolat an daste bandi ra neshan bede
    
                #----------    
    # baraie inke dar safhe product fagha mahsolati ra neshan bede ke marbot be daste bandi to dar to hastand
    category = Category.objects.filter(sub_cat=False)


    # if id:#agar id vojod dasht 
    #if slug: #aval ba id neveshtim vali alan ba slug
    if slug and id:#baraie inke ham slug va ham id ra neshan dahim
        # data = Category.objects.get(id=id)#yek daste bandi ke id an barabar id ast braie ma begir
        #agar karbar click kard roie daste bandi mahsolat han daste ra neshan bede. va nabaiad hame mahsolat ra neshan bedim va
        #product bala ra overwrite mikonim: yani na hame mahsolat ra mikhahim va na yek mahsol ra . va etelat khasi mikhahim va
        # az filter estefade mikonim
        # data = Category.objects.get(slug=slug)
        #ba ravesh bala dar error momken ast hak shavim ke az ravesh paein estefade mikonim
        data = get_object_or_404(Category, slug=slug, id=id)#baraie inke ham slug va ham id ra neshan dahim
        products = products.filter(category=data)


    return  render(request, 'home/product.html', {'products': products, 'category': category})

#------------------------------------------------------------------------------

#page jozeiat mahsol(detail)
def product_detail(request,id):
    #barie safhe jozeiat etelat takmili va form haie nazarsanji va... ra neshan midim
    # va az .all() estefade nemikonim va jozeiat haman mahsol ra neshan midahim
    # pas az get estefade mikonim ke begoeim haman yek mahsol khas ra neshan bede
    # va chon id uniqe ast bar asas an anjam midahim. va migoeim bro dakel model product va oni ke id az url baraie ma 
    # amade ra begi va barabar in id ghrar bedeh
    # Product.objects.get(id=id)

    # agar be sorat bala bashad momken ast mored hak gharar begirim banabar in az :
    #get_object_or_404 estefade mikonim ke yani ya an mahsol ra migirad ya agar nabod error 404 neshan midahad 
    product = get_object_or_404(Product, id=id)
    # # شرط می ذاریم که اگر محصولات ما رنگ بندی و سایز بندی داشتند و استتوسشان برابر  نان نبود 
# ----------------------------------------------
# این قسمت برای taggit
    similar = product.tags.similar_objects()[:2] # [:2] یعنی حداکثر 2 محصول مشابه را نشان دهد

# ----------------------------------------------

    if product.status is not None:  # != 'None' بجای این می توانیم بنویسیم اگر مخالف بود با . هردو درست است
        #که با متود پست و گت شرط می ذاریم که اگر پست بود یک کار و اگر گت بود یک کار
        if request.method == 'POST':  
            variant = Variaants.objects.filter(product_variants_id=id)
            var_id = request.POST.get('select')
            variants = Variaants.objects.get(id=var_id) 
        else:
            variant = Variaants.objects.filter(product_variants_id=id)
            variants = Variaants.objects.get(id=variant[0].id)
        context = {'product':product, 'variant':variant, 'variants':variants, 'similar':similar}    
        return render(request, 'home/detail.html', context)
#             variant= Variaants.objects.filter(product_variant_id=id)# برای اینکه با انتخاب ورینت توسط کاربر قیمت جدید را هم نمایش دهد 
#             #ریکوئست وظیفه اشتراک گذاری اطلاعات در معماری ام وی سی را برعهده دارد
#             var_id = request.POST.get('select') #ما قرار است درخواست را از کاربر بگیریم که با استفاده از ریکوئست است و باید حتما نام هم بدیم بهش
#             variants = Variaants.objects.get(id=var_id)
#         else: #اگر متود گت بود آن را
#             #باید از مدل ورینت استفاده کنیم . همچنین از فیلتر استفاده می کنیم تا اطلاهات خاص را نشان دهیم نه همه اطلاعات 
#             variant=Variaants.objects.filter(product_Variant_id=id)   # چون کلید خارجی داریم نمیتوانیم بگوئیم ایدی مساوی ایدی . 
#             #            چون محصول خودش درون یک  مدل دیگر است
#             # برای اینکه پیش فرض یک گزینه ورینت را انتخاب داشته باشد تا جنگو ارور ندهد
#             variants= Variaants.objects.get(id= variant[0].id) # ]چون یدانه را می خواهیم بصورت پیش فرض بگیریم و به کاربر نشان بدهبم

# #        return render(request, 'home/detail.html', {'product':product})# الان گفتیم محصول را نشان بده باز و رنگ و سایز را هم اضافه نشان بده
#         # چون باید هم پروداکت و هم دیکشنری انتخاب ورینت توسط کاربر را نشان دهیم بالا را کامنت می کنیم و بصورت زیر می نویسیم       
#         context = {'product':product, 'variant':variant, 'variants':variants}
#         return render(request, 'home/detail.html', context)
    else:
        return render(request, 'home/detail.html', {'product':product,'similar':similar},) 
        # سایز و رنگ نبود همینو نشان بده

mecacosite/home/templates/home/detail.html
{% extends 'base.html' %}
{% block title %} details {% endblock%} 

{% block body %}
<!-- chon yek meghdar ra mikhahim bargardanim for nemizanim -->
    <h1>{{ product.name}}</h1>
    <img src="{{ product.image.url }}" style="width: 500px; height: 300px;" alt=""><br>
    <!-- |safe نمایش تکست خودمان اضافه کنیم تا ارور ندهد برای سی کی ادیتور -->
    <p>{{ product.information|safe }}</p> 
    <hr>
    <!-- برای نمایش فرم ورینت و انتخاب آن توسط کاربر -->
    <!-- اگر ممحصول ما در دیتا بیس شامل سایز بندی است سایزبندی را و اگر رنگبندی دارد رنگ بندی را نشان دهد -->
    {% if product.status == 'Size' %} <!-- سایز با اس کوچک مقداری است که در استاتوس ورینت که سه مورد گذاشتیم را بر می گرداند -->
        <form action="" method="post">
        {% csrf_token %}
            {% for data in variant %} <!-- چون چندین سایز داریم از حلقه استفاده می کنیم -->

            <!-- برای مشخص کردن مقدار ورینت نمایش داده شده از ولیو استفاده می کنیم -->
            <!-- و چون هر سایز ما یک ای دی دارد برای نمایش مقدار می گوییم دیتا دات ای دی -->
            <!-- و برای اینکه کاربر فقط بتواند یکی را انتخاب کند یک شرط می گذاریم -->
            <!-- دیتا دات ایدی انتخاب کاربر را مشخص می کند -->
            <!-- و برای اینکه فقط یکی انتخاب شود از نام استفاده می کنیم و نام سلکت که در ویو برای ور ایدی گذاشته بودیم را می دهیم -->
             <!-- و حالا برای گرفتن مقدار از کاربر باید تایپ را سابمیت می گذاشتیم ولی چون قبلا از رادیو استفاده کردیم از انچنچ استفاده می کنیم -->
                <input type="radio" value="{{data.id}}" {% if variants.id == data.id %} checked {% endif %} 
                name="select" onchange="this.form.submit();">

                <!-- برای نمایش نام سایز مورد نظر یا همان ورینت و تکست دکوریشن برای برداشتن خط زیر ورینت در نمایش-->
                <a href="" style="text-decoration:none">{{data.size_variants}}</a> 
            {% endfor %}
        </form>

<!-- ************************************************************** -->
            <!-- حالا برای رنگ را هم مثل بالا انجام می دهیم -->
        {% elif product.status == 'Color' %}
            <form action="" method="post">
                {% csrf_token %}
                    {% for data in variant %}
                   
                        <input type="radio" value="{{data.id}}" {% if variants.id == data.id %} checked {% endif %} 
                        name="select" onchange="this.form.submit();">
                        <a href="" style="text-decoration:none">{{data.color_variants}}</a> 
                    {% endfor %}
                </form>
    {% endif %}
    <!-- -------------------------------------------- -->
    <!-- این قسمت برای نشان دادن محصولات مشابه توسط taggit -->
    <hr>
    
    {% for tag in similar %}
        <a href="{% url 'home:detail' tag.id %}">
            <img style="width: 200px; height: 200px;" src="{{tag.image.url}}" alt="">
        </a>
    {% endfor %}
        
    <!-- -------------------------------------------- -->
{% endblock body %}  

       
 

mecacosite/home/templates/home/home.html
{% extends 'base.html' %}
<!--baraie inke har safhe ra title an ra neshan dahad-->
{% block title %}
مکاکاکو سرویس
{% endblock %}
<!--baraie inke az base.html bekhanad tag body ra-->
{% block body %}
    <h1>Home page</h1>
    {% for data in category %}
        <!-- <h1>{{ data.name }}</h1> -->
        <!-- baraie link kardan az daste bandi be safhe mahsolat an ddaste bandi -->
        <!-- #baraie inke ham slug va ham id ra neshan dahim -->
        <!-- <a href="{% url 'home:category' data.slug data.id %}"> -->
             <!-- dar bala aval ba id kar kardim(data.id) va bade ba slug neveshtim(data.slug) -->
        <!-- chon category ra ba estefade az get_absolute_url meghdar dadim, digar url ra baiad avaz konim dar tag a      -->
        <a href="{{ data.get_absolute_url }}">
        <h1> {{ data.name }} </h1>
        </a>
        <!-- braie namaiesh picture -->
        <img src=" {{ data.image.url }}" style="width: 200; height: 150px;" alt="" >
        
    {% endfor %}
{% endblock %}

mecacosite/home/templates/home/product.html
{% extends 'base.html' %}
<!--baraie inke az base.html bekhanad tag body ra-->

{% block title %}
فروشگاه
{% endblock %}
{% block body %}
<h1>all product</h1>
<!-- baraie bootstrap yek for mizanim ta nam category ha ra begirim -->
{% for data in category%}
<!-- Example single danger button -->

<a href="{{ data.get_absolute_url}}">{{data.name}}</a>
<div class="btn-group">
    <button type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <!-- Action -->
    </button>
    <ul class="dropdown-menu">
        <!--  yek for daron for balaei mizanim ta nam  sub_category ha ra begirim va az daste bandi to dar to berim be category -->
        <!-- az related_name estefade mikonim ke name an ra 'sub' gozashte bodim va chon hame daste bandi ha ra mikhahim -->
        <!-- migoeim sub.all -->
        {% for info in data.sub.all %}
            <li><a class="dropdown-item" href="{{ info.get_absolute_url }}">{{info.name}}</a></li>
        {% endfor %}
    </ul>
</div>
{% endfor %}




<!-- baraie namaiesh mahsolat -->
{% for product in products %}
<h1>{{ product.name }}</h1>
<!-- link midahim az roie pic be safhe jozeiat(detail) -->
<!-- va chon dar url detail id ra gereftim inja ham baiad begirim -->
<a href="{% url 'home:detail' product.id %}">
    <img src="{{ product.image.url}}" style="width: 300px; height: 200px;" alt="">
</a>
<!-- <small>price: {{ product.unit_price}}</small> -->
<!-- if mizanim ta takfif vizhe ra neshan dahad -->
{% if product.discount %}
<h4 style="text-decoration: line-through ;">{{ product.unit_price }}</h4>
<h3>{{ product.total_price }}</h3>
{% else %}
<!-- agar takhfif vojod nadasht gheimat asli ra neshan bede     -->
<h3>{{ product.total_price }}</h3>
{% endif %}
{% endfor %}
{% endblock %}