mecacosite/accounts/urls.py
from unicodedata import name
from  django.urls import path
from .import views
app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('update/', views.user_update, name= 'update'), #5 baraie inke karbar profile khodesh ro update kone
    path('change/', views.change_password, name= 'change'),# baraie taghir password
    path('login_phone/', views.phone, name= 'phone'),#baraieneshan dadn form mobil
    path('verify/', views.verify, name= 'verify'),#baraie ferestadan karbar be safhe verify

]

mecacosite/home/urls.py
from django.urls import path, re_path
from .import views
app_name = 'home'
urlpatterns = [
    path('',views.home, name='home'),
    path('product/', views.all_product, name = 'product'),
    path('detail/<int:id>/', views.product_detail, name='detail'), # baraie safhe joziat mahsol. va  ba <id> migoem ke hamrah in url id 
    # ham miaiad va noee id ra ham moshakhas mikonim ke integer as
    # path('category/<int:id>/', views.all_product, name='category'),# vaghti roie oic yek category click kardim marabebarad 
    # be safe mahsolat . ama faghat mahsolat an daste ra neshan dahad. va views jadid neminevisim va az views all-product estefade m

    # alan url bala ke bevasile id kar mikard ra bevasile slug migoeim kar konad.
    # path('category/<slug:slug>/', views.all_product, name='category'),
    #vaghti ma az name daste bandi haie farsi estefadeh konim be ma error midahad dar url  haie ke ba slug misazim ya id:
    # pas baiad az re_path estefade konim va baiad az re_path(rejects) estefade konim vaki ma kalak mizanim va noesh ra nemigoeim
    # ke slug ast:
    # path('category/<slug>/', views.all_product, name='category'),
    
    # alan mikhahim dar url alave bar slug id ra ham dar url neshan dahad
    path('category/<slug>/<int:id>/', views.all_product, name='category'),


]  

mecacosite/mecacosite/urls.py
from django.contrib import admin
from django.urls import path, include

#baraie estefade az static aval do method zir ra farakhani mikonim va sepas path marbot be an ra ezafe mikonim:
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), # baraie amniat address admin ra taghir bedim
    path('',include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#baraie static va media file ha mibasha kod bala

mecacosite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<!--baraie inke title ma dar har page nam on page ra namaiesh dahad be sorat zir minevisim-->
    <title>{% block title %}{% endblock %}</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
      
<!--baraie static file ha va media file ha -->
    {% block css  %}{% endblock  %}
    
</head>
<body>
<!--baraie estefade az navbar-->
{% include 'navbar.html'%}

<!--baraie namaiesh message ha-->
{% include 'message.html'%}

<!--baraie inke mohtaviat home.html ra neshan dahad az block estefade mikonim-->
{% block body %}  {% endblock %}

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

mecacosite/templates/message.html
<!--baraie namayesh paiam ha aval shart mizarim ke aia payam vojod darad. va chon paiam ziad darim for mizanim-->

{% if messages %}
    {% for msg in messages %}
<!-- va shart migozarim ke agar dar message meghdar sevom yani extra tag vojod dasht bar asas hamon rang neshan bedeh-->
        <h5 {% if msg.tags %} class="alert alert-{{msg.tags}}" {% endif%}> {{ msg }} </h5>
<!--hala miravim file base.html va message ha ra be django moarefi konim-->
    {% endfor %}

{% endif %}

mecacosite/templates/navbar.html
<!--baraie estefade aznavbar miravim dar file base va includ mikonim-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:profile' %}">profile</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:product' %}">product</a>
        </li>
<!--yek shart migozarim agar karbar login nakarde bid logout ra neshan nadahad va agar login bod faghat logout neshan bede-->
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">logout</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:register' %}">register</a>
        </li>
       
        {% endif%}
      </ul>
    </div>
</nav>