mecacosite/accounts/urls.py
from unicodedata import name
from  django.urls import path
from .import views
app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('update/', views.user_update, name= 'update'), #5 baraie inke karbar profile khodesh ro update kone
    path('change/', views.change_password, name= 'change'),# baraie taghir password
    path('login_phone/', views.phone, name= 'phone'),#baraieneshan dadn form mobil
    path('verify/', views.verify, name= 'verify'),#baraie ferestadan karbar be safhe verify

]

mecacosite/home/urls.py
from django.urls import path, re_path
from .import views
app_name = 'home'
urlpatterns = [
    path('',views.home, name='home'),
    path('product/', views.all_product, name = 'product'),
    path('detail/<int:id>/', views.product_detail, name='detail'), # baraie safhe joziat mahsol. va  ba <id> migoem ke hamrah in url id 
    # ham miaiad va noee id ra ham moshakhas mikonim ke integer as
    # path('category/<int:id>/', views.all_product, name='category'),# vaghti roie oic yek category click kardim marabebarad 
    # be safe mahsolat . ama faghat mahsolat an daste ra neshan dahad. va views jadid neminevisim va az views all-product estefade m

    # alan url bala ke bevasile id kar mikard ra bevasile slug migoeim kar konad.
    # path('category/<slug:slug>/', views.all_product, name='category'),
    #vaghti ma az name daste bandi haie farsi estefadeh konim be ma error midahad dar url  haie ke ba slug misazim ya id:
    # pas baiad az re_path estefade konim va baiad az re_path(rejects) estefade konim vaki ma kalak mizanim va noesh ra nemigoeim
    # ke slug ast:
    # path('category/<slug>/', views.all_product, name='category'),
    
    # alan mikhahim dar url alave bar slug id ra ham dar url neshan dahad
    path('category/<slug>/<int:id>/', views.all_product, name='category'),


]  

mecacosite/mecacosite/urls.py
from django.contrib import admin
from django.urls import path, include

#baraie estefade az static aval do method zir ra farakhani mikonim va sepas path marbot be an ra ezafe mikonim:
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), # baraie amniat address admin ra taghir bedim
    path('',include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#baraie static va media file ha mibasha kod bala

mecacosite/accounts/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
# baraie ijad safhe karbari profile
# yani har karbar ke login kard safhe marbot be an ra neshan bedeh ke baiad az model User django komak begirim

#baraie format fhone
from phone_field import PhoneField

# baraie fhon az integerfield estefadeh kardim vali 0 ra neshan nemidahad va baiad 
# yek package be nam django-phone-field ke braie neshandadn 0 va save shodan dakhel DB ra darad
#va ba dastor pip install django-phone-field nasb mikonim. va bade miravim setting va install_app va ezafe mikonim
class Profile(models.Model):
    # har karbar ke login kard safhe marbot be an ra neshan bedeh
    user = models.OneToOneField(User, on_delete=models.CASCADE) #har karbar yek safhe darad pas yek be yek ast. 
    #migoeim ba class user rabete darad
    # phone = PhoneField(null=True, blank=True)#null va blank yani afar karbar meghdari vared bakard khata

    #phone ra fstring ham mitavanim moshkelash ra hal konim va nitavanim az phone field estefade nakonim
    phone = models.IntegerField(null=True, blank=True)
    #nadeh va profile an ra besaz
    address = models.CharField(max_length=200 , null=True, blank= True)

# baraie namayesh nam karbar dar fild haie safhe profile
    def __str__(self):
        return self.user.username # az object user ba klid yek be yek be class User dastresi darim

#--------------------------------------------------------------------------------------------------------------

# az signal zamani estefade mokonim ke agar etefaghi dar models ma oftad az an bakhabar beshavim va yek signal befrastad
# 7 ta signal darim
# 5taie aval(injalase kar badarim):


# from django.db.models.signals import post_save, pre_save, pre_delete, post_delete, m2m_changed

#post_save migoiad hargah dron DB chizi save shod etela bedeh
# pre_save migoiad ghabl az save shodan . yani karbar darkhast sabtnam mifrestad bakhabar kon
# pre_delete : ghabl az delete shodan khabar bede
# post delete migoiad bad az delete shodan bakhabar kon
# m2m baraie reletionship ast va taghir dar anha anjam shod khbar bedeh 

# 2taie badi
#request_finished yani agar dakhasti tamam shod khabar bedeh
#request_started ""     ""     ""    shoro shod khabar bedeh
# from django.core.signals import request_finished, request_started

#injalase ba post save kar darim. va migoeim ta karbar sabnam kard profile ra ham ijad kon:

from django.db.models.signals import post_save
# method connect bein frestande signal va girande signal ertebat barghrar mikonad. connect 2 ta meghdar migirad :
# 1- ye method ijad mikonim va girande ma mishavad method va bevasile an page profile khod ra ijad mikonim
# 2- sender ke ferastande ast ke dar inja models user ast . yani vaghti taghiri roie anjam shod signal befrestad 

def save_profile_user(sender, **kwargs): # tabe ma 2ta meghdar migirad: sender ke User mast va **kwargs ke etelaati ast ke az 
# taraf signal frestade mishe daron signal gharar migirad(mesle vaghti ke user jadid sakhte mishavad ke 2 ta meghdar migirad:1-
# created ke bolian ast va ya karbar sabtnam mikonad ya ba khata movajeeh mishavad manand email tekrari va ..  .2- instance: 
# etelaati ke karbar wared mikonad va ma migirim va yek user jadid ijad mikonim baraie hamin dar view dar function 
# user_register ma User.object.usre ra barabar yek meghdar ghara midahim masalan user)
    if kwargs['created']: # agar sabtnam karbar anjam shod
        profile_user = Profile(user=kwargs['instance']) # model Profile ra seda mizanim. moshkel ma user bod ke ba table
# User ertebat yek beyek dasht: va instance yani etelaati ke az objects user baraie ma gerefte bade sabtnam karbar ra migirim(
# user ke dar views ijad kardim) va barabar ba uek motaghair gharr midahim ke dar inja profile_user ast
        profile_user.save()# va dar akhar save mikonim
post_save.connect(save_profile_user, sender= User)

mecacosite/accounts/views.py
from email import message
import profile
from django.shortcuts import render,redirect

# from mecacosite import accounts
# from .forms import UserRegisterForm    dar in ravash tak tak form ha ra baiad seda bezanim vali agar * bezarim
# digar niazi nist tak tak seda konim
from .forms import *
from .models import *
from django.contrib.auth.models import User
#baraie baresi mojjod bodan user pass dar DB
from django.contrib.auth import authenticate, login, logout

#baraie estefade az messages va namayesh paiam ha
from django.contrib import messages

#baraie change password
from django.contrib.auth.forms import PasswordChangeForm
# baraie session ha ast va vaghti ke password ra avaz mikonim sessions haie ghabli ra bebandad


#baraie inke karbar vaghti login nakarde natavanad profile khod ra bebinad va hamchenin update va change profile ra az 
# decorators estefade mikonim ke raftar tabe ra avaz mikonad
# va az method login_required estefade mikonim. alan dar update va profile estefade mikonim
from django.contrib.auth.decorators import login_required

from random import randint

"""
@agar user az tarigh method get vared shod form ra neshan bede
 
"""
def user_register(request):
    if request.method == 'POST':
        # vaghti karbar aztarigh method post vard beshavad be form elam mikonim.
        form = UserRegisterForm(request.POST)
        # hala shart mizarim ke agar etelaat karbar tamiz bod sabt nam ra anjam bedeh(kod mokhareb ya email sahih , adad ,...)
        if form.is_valid():
            # is valid 3 method digar ra farakhani mikonad ke outomatic etebar sanji mikonad va etelaat ra dakhel dictionary
            #mirizad va etelat ra ma az anja mikhanad
            data = form.cleaned_data
            #hala user ra ijad mikonim . va objects baraie ertebat ba models ma mibashad.
            # alan 5 ta meghdar migirim. migoeim username ra az meghdar haie clean begir
            # User.objects.create_user(username=data['user_name'], email=data['email'], first_name=data['first_name'],
            #                          last_name=data['last_name'], password=data['password_2'])
            #allan bade etmam sabt nam karbar ra mifrestim page home chon felan safhe login nadarim

            #signal:
            #baraie estefade az signal kol tabe zir ra barabar user(name ekhtiari ast) gharar midahim
            user = User.objects.create_user(username=data['user_name'], email=data['email'], first_name=data['first_name'],
                                     last_name=data['last_name'], password=data['password_2'])

            # baraie estefade az signal save user bala ra besorat zir:
            user.save()
            return redirect('home:home')#aval esme app va bad safhe ke mikhahim beravim va name url an


    # dar else migoeim agar get bod form ra neshan bede
    else:
        form = UserRegisterForm()
    context = {'form':form}
    return render(request, 'accounts/register.html', context)

#-------------------------------------------------------------------------------------------------------------
# # for login form ba base username
# #moshakhas mikonim agar method post bod yek kar va get bod yekar digar
# def user_login(request):
#     if request.method == 'POST':
#         form = UserLoginForm(request.POST)
#         # hala baraie validation
#         if form.is_valid(): # data ha ra mirizad dakhel dictionary cleanData
#             data = form.cleaned_data
#             # hala check konim username va pass dar DB vojod dard ya na
#             user = authenticate(request,username=data['user'], password=data['password'])
#             #agar user va pass sahih bashad authenticate meghdar clean shode ra mirizad dar user va agar eshtebah bashad
#             #null barmigardanad
#             if user is not None:  # agar meghdar khali nabod
#                 login(request,user) # ba method login karbar ra login mikonim
#                 #bad az login befrest be home page
#                 return redirect('home:home')
#
#
#     # agar GET bod ya user pass eshtebah bod
#     else:
#         form = UserLoginForm()
#     return render(request,'accounts/login.html',{'form':form})

#-------------------------------------------------------------------------------------------------------
# for login form ba base username va email
#moshakhas mikonim agar method post bod yek kar va get bod yekar digar
def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        # hala baraie validation
        if form.is_valid(): # data ha ra mirizad dakhel dictionary cleanData
            data = form.cleaned_data
            try: # baraie login ba username va ba email. try aval saei mikonad ba email va agar username ra ham vared
                #kard baz login kon
                # hala check konim username va pass dar DB vojod dard ya na
                user = authenticate(request,username=User.objects.get(email=data['user']), password=data['password'])
            except:
                user = authenticate(request, username=data['user'], password=data['password'])
            #agar user va pass sahih bashad authenticate meghdar clean shode ra mirizad dar user va agar eshtebah bashad
            #null barmigardanad
            if user is not None:  # agar meghdar khali nabod
                login(request,user) # ba method login karbar ra login mikonim
                #bad az login befrest be home page

                # baraie namayesh message ha. va 'primary' ha rang ra moshakhas mikonad. hala mira vim be file message
                # va shart migozarim ke agar dar message meghdar sevom yani extra tag vojod dasht
                #bar asas hamon rang neshan bedeh
                messages.success(request,'خوش امدید وارد شدید', 'primary')
                return redirect('home:home')
                #agar user pass eshtebah bod message dahad va 'danger' baraie rang an
            else:
                messages.error(request, 'پسورد اشتباه است', 'danger')


    # agar GET bod ya user pass eshtebah bod
    else:
        form = UserLoginForm()
    return render(request,'accounts/login.html',{'form':form})

#*************************************************************************************************

#for logout
def user_logout(request):
    logout(request)
    #vaghti logout kard paiam neshan bedeh. (seccess va error farghi nadaran ba ham). baiad brim dar template root file
    #message.html ijad konim
    messages.success(request, 'با موفقیت خارج شدید', 'warning')
    return redirect('home:home')

#**************************************************************************************************

#4 baraie ijad safhe karbari profile. ke baiad model besazim

# decorators estefade mikonim ke ta karbar login nakarde ejaze nadahad vared safhe shavad. ke az @ estefade mikonim va
# yek login_url= migirad ke moshakhas mikonim karbar agar khast beravad be profile aval befrest be login

@login_required(login_url='accounts:login')
def user_profile(request):
    #neshan dadan fildha be karbaran ba estefade az id
    #id karbari ke darkhast dade ra begir
    profile = Profile.objects.get(user_id=request.user.id)
    # baraie namaiesh mohtava ha anha ra dar dictionary gharar midahim
    return render(request, 'accounts/profile.html',{'profile':profile})

#***********************************************************************************************
#warning : felan khata darad va do form user va profile ra baaham neshan nemidahad

#5 baraie inke karbar profile khodesh ro update kone

# def user_update(request):
#     #namayesh dota form update User,Profile
#     #aval moshakhas konim agar az GET omade form ro neshan bedim
#     if request.method == 'POST':
#         user_form = UserUpdateForm(request.POST, instance=request.User)
#         profile_form = ProfileUpdateForm(request.POST, instance=request.user.profile)

#     #alan chon 2ta form darim baiad chek konim ke form(dakhast karbar) drost ast ya na
#         if user_form and profile_form.is_valid():
#             # etelaat ra daron DB save mikonim
#             user_form.save()
#             profile_form.save()
#         # vaghti hame chiz drost bod ye message neshan midahim.    success style rang message ast
#             messages.success(request, 'update successfully', 'success')
#             return redirect('accounts:profile')
#     else:
#         #da ghei insorat agar method GET bod 2 ta form mara namayesh bede
#         user_form = UserUpdateForm()
#         profile_form = ProfileUpdateForm()
#     # baraie namayesh etelaat be karbar baiad dron yek dictionary daron tabe render berizim ta da file html dashte bashimash
#     context = {'user_form':user_form, 'profile_form':profile_form}
#     # context ra dar render gharar midahim
#     return render(request, 'accounts/update.html', context)

                #.........................
                
# decorators estefade mikonim ke ta karbar login nakarde ejaze nadahad vared safhe shavad. ke az @ estefade mikonim va
# yek login_url= migirad ke moshakhas mikonim karbar agar khast beravad be profile aval befrest be login

@login_required(login_url='accounts:login')
def user_update(request):
    #namayesh dota form update User,Profile
    #aval moshakhas konim agar az GET omade form ro neshan bedim
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        #instance baraie inke meghdar haie mojod ra be karbar neshan dahim ta karbar bebinad va agar khast taghir dahad
        #va baiad aval maghadir ra az database begirim. baraie method GET ke dar else goftim ham instance ra ghara midahim

        # profile_form = ProfileUpdateForm(request.POST, instance=request.user.profile)

    #alan chon 2ta form darim baiad chek konim ke form(dakhast karbar) drost ast ya na
        if user_form.is_valid():
            # etelaat ra daron DB save mikonim
            user_form.save()
            profile_form.save()

mecacosite/accounts/templates/accounts/change.html
{% extends 'base.html' %}
{% block title %}
change
{% endblock %}

{% block body %}
<h1>change password</h1>
    <form method="post" action="">
        {% csrf_token %}
        <!-- baraie inke neveshtehaie defult django baraie pass ra bardarim kod zir ra comment va field ha ra tak tak seda mizanim -->
        <!-- ravesh asli : --> 
        {{ form.as_p }}

        <!-- revesh 2 : -->

            <!-- {{ form.old_password}} <br><br>
            {{ form.new_password1 }} <br><br>
            {{ form.new_password2 }} <br><br> -->

        <!-- ravesh 3 : -->
        <!-- <!-- <input type="password" name= "old_password" placeholder="پسورد قبلی"><br><br>
        <input type="password" name= "password1" placeholder="پسورد جدید"><br><br>
        <input type="password" name= "password2" placeholder="تکرار پسورد "><br><br> -->
        
        
        <button type="submit">تایید</button>
        
    </form>
    <!-- baraie inke dar page change ma message haie django ra hazf konim style midahim ke ul ke message ha daron an ast none shavad -->
    <style>
        form ul{
            display: none;
        }
    </style>
{% endblock %}


<!-- alan baraie ma neshan midahad form taghir passwoer ra vali neveshte ha englesh hastand va baiad beravim be -->
<!-- setting va ghesmat AUTH-PASSWORD va az anja 4 shart pass ra farsi mikonim -->

mecacosite/accounts/templates/accounts/code.html
{% extends 'base.html' %}
{% block body %}
<h1> phone login</h1>
    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type= "submit" >login</button>
    </form>
{% endblock  %} 

mecacosite/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}
login
{% endblock %}

{% block body %}
<h1>login page</h1>
    <form method="post" novalidate>
    {% csrf_token %}
<!--        {{ form.as_p }}-->
<!--        baraie taghir namayesh form va neshan dadn username dakhel filde  tag form ra be sorat zir-->
<!--        {{ form.user }}<br><br>-->
<!--        {{ form.password }}<br><br>-->

<!--        ba html input bedahim-->
        <input type="text" name="user" placeholder="نام کاربری را وارد کنید"><br><br>
        <input type="password" name="password" placeholder="پسورد را وارد کنید"><br><br>

        <button type="submit">login</button>

    </form>
{% endblock %}
#------------------------------------------------------------------------------------------------

mecacosite/accounts/templates/accounts/phone.html
{% extends 'base.html' %}
{% block title %}
phone login
{% endblock %}

{% block body %}
<h1>phone login</h1>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">send cod</button>
    </form>
{% endblock %}

mecacosite/accounts/templates/accounts/profile.html
<!-- baraie ijad safhe karbari profile-->
{% extends 'base.html' %}
{% block title %}
profile
{% endblock %}

{% block body %}
<h1>profile</h1>
<!--baraie namaiesh porofile karbar-->

<!-- <table> -->
    <!-- <tr> -->
<!--        chon profile ba user klid yek be yek darand ma be user_name,... dastresi darim-->
        <!-- <th>user: {{ profile.user.username }}</th> -->
    <!-- </tr> -->
    <!-- <tr> -->
        <!-- <th> name: {{profile.user.first_name}}</th> -->
    <!-- </tr> -->
    <!-- <tr> -->
        <!-- <th> last_name: {{profile.user.last_name}}</th> -->
    <!-- </tr> -->
    <!-- <tr> -->
        <!-- <th> email: {{profile.user.email}}</th> -->
    <!-- </tr> -->
    <!-- <tr> -->
        <!-- <th>phone: {{ profile.phone }}</th> -->
    <!-- </tr> -->
    <!-- <tr> -->
        <!-- <th> address: {{profile.address}}</th> -->
    <!-- </tr> -->
<!-- </table> -->
<!-- baraie update kardan safhe profile -->
<!-- <a href="{% url 'accounts:update'%}">update_profile</a> -->

<!-- baraie taghir password -->
<!-- <a href="{% url 'accounts:change' %}">change pass</a> -->


<!-- namayesh page profile ba bootstrap -->

<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted">name: {{profile.user.first_name}}</h6>
        <h6 class="card-subtitle mb-2 text-muted">last_name: {{profile.user.last_name}}</h6>
        <h6 class="card-subtitle mb-2 text-muted">email: {{profile.user.email}}</h6>
        <h6 class="card-subtitle mb-2 text-muted">phone: {{ profile.phone }}</h6>
        <h6 class="card-subtitle mb-2 text-muted">address: {{profile.address}}</h6>
      
      <!-- baraie update kardan safhe profile -->
        <a href="{% url 'accounts:update'%}">update</a>

      <!-- baraie taghir password -->
        <a href="{% url 'accounts:change' %}">change</a>
    </div>
  </div>
{% endblock %}

mecacosite/accounts/templates/accounts/register.html
<!--bad az inke view form sabte nam ra neveshtim baiad inja ra dorost konim . method besorat pish farz get ast-->
{% extends 'base.html'%}
<!-- baraie inke az static estefade konim az tag load estefade mikonim-->
{% load static %}
{% block title %}
register
{% endblock %}
<!-- alan dar tag head block css ra ijad mikonim ta beshnasad -->
{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/register.css' %}">
{% endblock  %}

{% block body %}
<!--novalidate baraie etebar sanji django ast va badan farsish mikonim-->
    <form method="post" novalidate>
<!--        baraie jologiri azhamalat baiad tag crftoken bezarim-->
         {% csrf_token %}
<!--       baraie namaiesh form dakhel akolad motaghaieri  ke class formeman ra barabash gharar dadim mizarim ke inja form ast  -->
<!--        baraie namaiesh behtar form mitavan as_p ( besorat parageraf va as_table va as_ul ke behtarinash as_p ast)-->
        {{ form.as_p }}
<!--        baraie submit kardan-->
        <button type="submit">reqister</button>
    
    </form>
{% endblock %}

mecacosite/accounts/templates/accounts/update.html
<!-- baraie update kardan profile -->
{% extends 'base.html' %}
{% block title %}
update profile
{% endblock %}

{% block body %}
<h1>update profile</h1>
<!-- baraie namayesh 2ta form user va profile ke sakhtim -->
<form action="" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p}}
<button type="submit">update</button>


</form>

{% endblock %}

mecacosite/accounts/templates/accounts/verify.html
{% extends 'base.html' %}
{% block title %}

{% endblock  %}

{% block body %}
<h1>phone login</h1>
{% endblock  %}